jwt:
  secret: 'AshuSingh'

server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

